# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x06protos\"\x85\x01\n\x08TodoItem\x12\r\n\x05title\x18\x01 \x01(\t\x12+\n\x06status\x18\x02 \x01(\x0e\x32\x1b.protos.TodoItem.TodoStatus\"=\n\nTodoStatus\x12\x0f\n\x0bNOT_STARTED\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\r\n\tCOMPLETED\x10\x02\"+\n\x08TodoList\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.protos.TodoItem\"\x1f\n\x0cTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x07\n\x05\x65mpty2\xcd\x01\n\x0bTodoManager\x12\x31\n\x07\x41\x64\x64Todo\x12\x10.protos.TodoItem\x1a\x14.protos.TodoResponse\x12\x32\n\x08\x45\x64itTodo\x12\x10.protos.TodoItem\x1a\x14.protos.TodoResponse\x12*\n\x07\x44\x65lList\x12\r.protos.empty\x1a\x10.protos.TodoList\x12+\n\x08GetTodos\x12\r.protos.empty\x1a\x10.protos.TodoListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TODOITEM._serialized_start=23
  _TODOITEM._serialized_end=156
  _TODOITEM_TODOSTATUS._serialized_start=95
  _TODOITEM_TODOSTATUS._serialized_end=156
  _TODOLIST._serialized_start=158
  _TODOLIST._serialized_end=201
  _TODORESPONSE._serialized_start=203
  _TODORESPONSE._serialized_end=234
  _EMPTY._serialized_start=236
  _EMPTY._serialized_end=243
  _TODOMANAGER._serialized_start=246
  _TODOMANAGER._serialized_end=451
# @@protoc_insertion_point(module_scope)
