# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import todo_pb2 as todo__pb2


class TodoManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTodo = channel.unary_unary(
                '/protos.TodoManager/AddTodo',
                request_serializer=todo__pb2.TodoItem.SerializeToString,
                response_deserializer=todo__pb2.TodoResponse.FromString,
                )
        self.EditTodo = channel.unary_unary(
                '/protos.TodoManager/EditTodo',
                request_serializer=todo__pb2.TodoItem.SerializeToString,
                response_deserializer=todo__pb2.TodoResponse.FromString,
                )
        self.DelList = channel.unary_unary(
                '/protos.TodoManager/DelList',
                request_serializer=todo__pb2.empty.SerializeToString,
                response_deserializer=todo__pb2.TodoList.FromString,
                )
        self.GetTodos = channel.unary_unary(
                '/protos.TodoManager/GetTodos',
                request_serializer=todo__pb2.empty.SerializeToString,
                response_deserializer=todo__pb2.TodoList.FromString,
                )


class TodoManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTodo,
                    request_deserializer=todo__pb2.TodoItem.FromString,
                    response_serializer=todo__pb2.TodoResponse.SerializeToString,
            ),
            'EditTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.EditTodo,
                    request_deserializer=todo__pb2.TodoItem.FromString,
                    response_serializer=todo__pb2.TodoResponse.SerializeToString,
            ),
            'DelList': grpc.unary_unary_rpc_method_handler(
                    servicer.DelList,
                    request_deserializer=todo__pb2.empty.FromString,
                    response_serializer=todo__pb2.TodoList.SerializeToString,
            ),
            'GetTodos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTodos,
                    request_deserializer=todo__pb2.empty.FromString,
                    response_serializer=todo__pb2.TodoList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.TodoManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TodoManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.TodoManager/AddTodo',
            todo__pb2.TodoItem.SerializeToString,
            todo__pb2.TodoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.TodoManager/EditTodo',
            todo__pb2.TodoItem.SerializeToString,
            todo__pb2.TodoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DelList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.TodoManager/DelList',
            todo__pb2.empty.SerializeToString,
            todo__pb2.TodoList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.TodoManager/GetTodos',
            todo__pb2.empty.SerializeToString,
            todo__pb2.TodoList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
